SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `multicard` (
  `id` int(50) NOT NULL,
  `tipologia` varchar(255) NOT NULL,
  `codice` varchar(255) NOT NULL,
  `veicolo` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `multicard` (`id`, `tipologia`, `codice`, `veicolo`) VALUES
(1, 'Eni', '1234567890', 1),
(2, 'Q8', '0987542344', 9999);

CREATE TABLE `telepass` (
  `id` int(50) NOT NULL,
  `codice` varchar(255) NOT NULL,
  `veicolo` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `telepass` (`id`, `codice`, `veicolo`) VALUES
(1, '1234567123', 2);


ALTER TABLE `multicard`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `telepass`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `multicard`
  MODIFY `id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

ALTER TABLE `telepass`
  MODIFY `id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
